apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel-core.fullname" . }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "database.url is required" .Values.database.url | quote }}
  REDIS_URL: {{ required "redis.url is required" .Values.redis.url | quote }}
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  ENTERPRISE_AUTH_TOKEN: {{ required "secrets.enterpriseAuthToken is required" .Values.secrets.enterpriseAuthToken | quote }}
  CA_CERT_PEM: {{ required "secrets.caCertPEM is required" .Values.secrets.caCertPEM | quote }}
  CA_KEY_PEM: {{ required "secrets.caKeyPEM is required" .Values.secrets.caKeyPEM | quote }}
  JWT_PRIVATE_KEY_PEM: {{ required "secrets.jwtPrivateKeyPEM is required" .Values.secrets.jwtPrivateKeyPEM | quote }}
  JWT_PUBLIC_KEY_PEM: {{ required "secrets.jwtPublicKeyPEM is required" .Values.secrets.jwtPublicKeyPEM | quote }}
  JWT_KEY_ID: {{ required "secrets.jwtKeyID is required" .Values.secrets.jwtKeyID | quote }}
  JWT_REVOCATION_VERSION: {{ .Values.secrets.jwtRevocationVersion | quote }}
  JWT_ISSUER: {{ .Values.secrets.jwtIssuer | quote }}
  JWT_AUDIENCE: {{ .Values.secrets.jwtAudience | quote }}
