apiVersion: v1
kind: Secret
metadata:
  name: {{ include "sentinel-core.fullname" . }}
type: Opaque
stringData:
  DATABASE_URL: {{ required "database.url is required" .Values.database.url | quote }}
  REDIS_URL: {{ .Values.redis.url | quote }}
  JWT_SECRET: {{ required "secrets.jwtSecret is required" .Values.secrets.jwtSecret | quote }}
  ENTERPRISE_AUTH_TOKEN: {{ required "secrets.enterpriseAuthToken is required" .Values.secrets.enterpriseAuthToken | quote }}
