apiVersion: v1
kind: Service
metadata:
  name: {{ include "sentinel-core.fullname" . }}
  labels:
    app: {{ include "sentinel-core.fullname" . }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "sentinel-core.fullname" . }}
  ports:
    - name: public
      port: {{ .Values.service.publicPort }}
      targetPort: public
    - name: private
      port: {{ .Values.service.privatePort }}
      targetPort: private
